version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: leaderboard
      POSTGRES_PASSWORD: leaderboard
      POSTGRES_DB: leaderboard
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leaderboard -d leaderboard"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: leaderboard
      DB_PASSWORD: leaderboard
      DB_NAME: leaderboard
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure

volumes:
  db_data: 